language: python
python:
    - 3.6
install:
    - pip install boto3
    - pip install utils
    - pip install moto
    - pip install psycopg2
    - pip install coverage
    - pip install google_compute_engine
    - pip install pytest
branches:
    only:
        - master
        - develop
addons:
    sonarcloud:
        organization: "usdot-jpo-sdc-projects"
       
script: 
    - coverage erase
    - coverage run -m pytest tests/
    - coverage xml -i
    - sonar-scanner -X -D sonar.login=$SONAR_TOKEN
